- name: Install system packages
  hosts: localhost
  become: true
  tasks:
    - name: Add Starship copr
      community.general.copr:
        name: atim/starship
    - name: Add Lazygit copr
      community.general.copr:
        name: atim/lazygit
    - name: Install packages from dnf
      ansible.builtin.dnf:
        name:
          - alacritty
          - curl
          - direnv
          - fd-find
          - firefox
          - fzf
          - gnome-tweaks
          - gimp
          - git
          - keepassxc
          - lazygit
          - neovim
          - nodejs
          - openssh
          - podman
          - ripgrep
          - starship
          - stow
          - thunderbird
          - tmux
          - transmission
          - tree
          - vim
          - vlc
          - "@C Development Tools and Libraries"
        state: latest
        update_cache: true

- name: Personal setup
  hosts: localhost
  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
  tasks:
    - name: Run tasks
      ansible.builtin.include_tasks:
        file: "{{ task }}"
      loop:
        - tasks/atuin.yml
        - tasks/nvm.yml
        - tasks/uv.yml
        - tasks/dotfiles.yml
        - tasks/neovim.yml
      loop_control:
        loop_var: task
