- name: Install system packages
  hosts: localhost
  become: true
  tasks:
    - community.general.copr:
        name: atim/starship
    - community.general.copr:
        name: atim/lazygit
    - community.general.copr:
        name: agriffis/neovim-nightly
    - ansible.builtin.dnf:
        name:
          - alacritty
          - curl
          - direnv
          - fd-find
          - fzf
          - git
          - lazygit
          - neovim
          - nodejs
          - openssh
          - podman
          - python3-neovim
          - ripgrep
          - starship
          - stow
          - tmux
          - tree
          - vim
          - "@C Development Tools and Libraries"
        state: latest
        update_cache: true

- name: Personal setup
  hosts: localhost
  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
  tasks:
    - ansible.builtin.include_tasks:
        file: "{{ task }}"
      loop:
        - tasks/atuin.yml
        - tasks/nvm.yml
        - tasks/pyenv.yml
        - tasks/dotfiles.yml
        - tasks/neovim.yml
      loop_control:
        loop_var: task
