- name: Download bash-preexec script, required for atuin with bash
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh
    dest: "{{ home }}/.bash-preexec.sh"

- name: Install atuin with cargo
  community.general.cargo:
    name: atuin
