- name: Check if .nvm directory exists
  ansible.builtin.file:
    path: "{{ home }}/.nvm"
    state: directory
    mode: "0755"


- name: Install nvm
  ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | sh
