- name: Check if .pyenv directory exists
  ansible.builtin.stat:
    path: "{{ home }}/.pyenv"
  register: pyenv

- name: Install pyenv
  ansible.builtin.shell: curl https://pyenv.run | sh
  when: pyenv.stat.isdir is not defined
